[project]
name = "golgotha"
version = "1.1.1"
dependencies = ["regex"]
requires-python = ">= 3"
authors = [
  {name = "Wyatt S Carpenter"}
]
maintainers = [
  {name = "Wyatt S Carpenter"}
]
description = "A preprocessor to define new operators in any programming language."
readme = "readme.md"
keywords = ["preprocessor", "operators", "infix", "prefix", "postfix", "syntax", "💀", "🔣"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Pre-processors",
]
license = "CC0-1.0 AND MIT-0"

[project.urls]
Homepage = "https://github.com/wyattscarpenter/golgotha"
Documentation = "https://github.com/wyattscarpenter/golgotha/blob/master/readme.txt"
Repository = "https://github.com/wyattscarpenter/golgotha.git"
Issues = "https://github.com/wyattscarpenter/golgotha/issues"

[project.scripts]
golgotha = "golgotha:main"

[dependency-groups]
# These "dev" packages will let you actually build (and test) this python program. Also, my build system is just running `uv run ./pypi.bat` — which runs check.bat first and stops if it fails, which is the important part. I put all correctness checks in the pipeline for the build so they can all check the correctness of the program before it gets distributed. The final part of the build process also seems to install "setuptools >= 40.8.0" multiple times during the build/twine step, probably for isolation/reproducibility purposes.
# You should also have git installed, as the test script uses git diff; and optionally wsl (Windows-Subsystem-for-Linux — not to be confused with apt's wsl, which is different) which allows you to run sdiff on Windows. But there is no way to notate those requirements. Arguably I should get rid of these requirements and just use some python-native (s)diffing package, but I don't feel like changing that is worth my time at the moment.
dev = ["types-regex", "ruff", "mypy", "pyright", "build", "twine"]
